### ISSUE TITLE
Error in version 0.1.0 (typst/packages)

### ISSUE THREAD

**Issue by jamesrswift** [tingerrr/typst-anti-matter#1]
https://github.com/tingerrr/anti-matter/blob/ebdf1a8207cd4c256775b1e279fe35febc5ad4bb/src/lib.typ#L18

Above line is from this repo (tingerrr/anti-mater)
Below line is from typst/packages

https://github.com/typst/packages/blob/3e450dcd3dcf23e74b10b3e557acb223928ce308/packages/preview/anti-matter/0.1.0/src/lib.typ#L18

Maybe a small update that doesn't increment semver to fix?

**Comment by tingerrr** [comment]
Yeah, that happens when you rewrite the package while being tired, I've lined up a fix already here: [packages#268](https://github.com/typst/packages/pull/268).

**Comment by tingerrr** [comment]
Fixed in [v0.1.1](https://github.com/typst/packages/pull/268).
